package model;

public class Estado {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Estado.id
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Estado.descripcion
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    private String descripcion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Estado.id
     *
     * @return the value of Estado.id
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Estado.id
     *
     * @param id the value for Estado.id
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Estado.descripcion
     *
     * @return the value of Estado.descripcion
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Estado.descripcion
     *
     * @param descripcion the value for Estado.descripcion
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
}