package model;

public class Estudiante {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Estudiantes.id
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Estudiantes.nombre
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    private String nombre;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Estudiantes.apellido
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    private String apellido;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Estudiantes.correo
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    private String correo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Estudiantes.edad
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    private Integer edad;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Estudiantes.celular
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    private String celular;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Estudiantes.id
     *
     * @return the value of Estudiantes.id
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Estudiantes.id
     *
     * @param id the value for Estudiantes.id
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Estudiantes.nombre
     *
     * @return the value of Estudiantes.nombre
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Estudiantes.nombre
     *
     * @param nombre the value for Estudiantes.nombre
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Estudiantes.apellido
     *
     * @return the value of Estudiantes.apellido
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public String getApellido() {
        return apellido;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Estudiantes.apellido
     *
     * @param apellido the value for Estudiantes.apellido
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Estudiantes.correo
     *
     * @return the value of Estudiantes.correo
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public String getCorreo() {
        return correo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Estudiantes.correo
     *
     * @param correo the value for Estudiantes.correo
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public void setCorreo(String correo) {
        this.correo = correo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Estudiantes.edad
     *
     * @return the value of Estudiantes.edad
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public Integer getEdad() {
        return edad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Estudiantes.edad
     *
     * @param edad the value for Estudiantes.edad
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public void setEdad(Integer edad) {
        this.edad = edad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Estudiantes.celular
     *
     * @return the value of Estudiantes.celular
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public String getCelular() {
        return celular;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Estudiantes.celular
     *
     * @param celular the value for Estudiantes.celular
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public void setCelular(String celular) {
        this.celular = celular;
    }
}