package model;

public class EstudianteMateria {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Estudiantes_Materias.id
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Estudiantes_Materias.id_estudiantes
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    private Integer idEstudiantes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Estudiantes_Materias.id_materia
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    private Integer idMateria;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Estudiantes_Materias.id
     *
     * @return the value of Estudiantes_Materias.id
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Estudiantes_Materias.id
     *
     * @param id the value for Estudiantes_Materias.id
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Estudiantes_Materias.id_estudiantes
     *
     * @return the value of Estudiantes_Materias.id_estudiantes
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public Integer getIdEstudiantes() {
        return idEstudiantes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Estudiantes_Materias.id_estudiantes
     *
     * @param idEstudiantes the value for Estudiantes_Materias.id_estudiantes
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public void setIdEstudiantes(Integer idEstudiantes) {
        this.idEstudiantes = idEstudiantes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Estudiantes_Materias.id_materia
     *
     * @return the value of Estudiantes_Materias.id_materia
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public Integer getIdMateria() {
        return idMateria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Estudiantes_Materias.id_materia
     *
     * @param idMateria the value for Estudiantes_Materias.id_materia
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public void setIdMateria(Integer idMateria) {
        this.idMateria = idMateria;
    }
}