package model;

public class Materia {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Materias.id
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Materias.nombre_materia
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    private String nombreMateria;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Materias.id
     *
     * @return the value of Materias.id
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Materias.id
     *
     * @param id the value for Materias.id
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Materias.nombre_materia
     *
     * @return the value of Materias.nombre_materia
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public String getNombreMateria() {
        return nombreMateria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Materias.nombre_materia
     *
     * @param nombreMateria the value for Materias.nombre_materia
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public void setNombreMateria(String nombreMateria) {
        this.nombreMateria = nombreMateria;
    }
}