package model;

import java.math.BigDecimal;

public class NotaPrimerParcial {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notas_primer_parcial.id_nota
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    private Integer idNota;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notas_primer_parcial.id_estudiante
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    private Integer idEstudiante;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notas_primer_parcial.nota_deberes
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    private BigDecimal notaDeberes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notas_primer_parcial.nota_asistencia
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    private BigDecimal notaAsistencia;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notas_primer_parcial.nota_leccion
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    private BigDecimal notaLeccion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notas_primer_parcial.nota_examen
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    private BigDecimal notaExamen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notas_primer_parcial.promedio
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    private BigDecimal promedio;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notas_primer_parcial.id_nota
     *
     * @return the value of notas_primer_parcial.id_nota
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public Integer getIdNota() {
        return idNota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notas_primer_parcial.id_nota
     *
     * @param idNota the value for notas_primer_parcial.id_nota
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public void setIdNota(Integer idNota) {
        this.idNota = idNota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notas_primer_parcial.id_estudiante
     *
     * @return the value of notas_primer_parcial.id_estudiante
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public Integer getIdEstudiante() {
        return idEstudiante;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notas_primer_parcial.id_estudiante
     *
     * @param idEstudiante the value for notas_primer_parcial.id_estudiante
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public void setIdEstudiante(Integer idEstudiante) {
        this.idEstudiante = idEstudiante;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notas_primer_parcial.nota_deberes
     *
     * @return the value of notas_primer_parcial.nota_deberes
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public BigDecimal getNotaDeberes() {
        return notaDeberes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notas_primer_parcial.nota_deberes
     *
     * @param notaDeberes the value for notas_primer_parcial.nota_deberes
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public void setNotaDeberes(BigDecimal notaDeberes) {
        this.notaDeberes = notaDeberes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notas_primer_parcial.nota_asistencia
     *
     * @return the value of notas_primer_parcial.nota_asistencia
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public BigDecimal getNotaAsistencia() {
        return notaAsistencia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notas_primer_parcial.nota_asistencia
     *
     * @param notaAsistencia the value for notas_primer_parcial.nota_asistencia
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public void setNotaAsistencia(BigDecimal notaAsistencia) {
        this.notaAsistencia = notaAsistencia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notas_primer_parcial.nota_leccion
     *
     * @return the value of notas_primer_parcial.nota_leccion
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public BigDecimal getNotaLeccion() {
        return notaLeccion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notas_primer_parcial.nota_leccion
     *
     * @param notaLeccion the value for notas_primer_parcial.nota_leccion
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public void setNotaLeccion(BigDecimal notaLeccion) {
        this.notaLeccion = notaLeccion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notas_primer_parcial.nota_examen
     *
     * @return the value of notas_primer_parcial.nota_examen
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public BigDecimal getNotaExamen() {
        return notaExamen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notas_primer_parcial.nota_examen
     *
     * @param notaExamen the value for notas_primer_parcial.nota_examen
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public void setNotaExamen(BigDecimal notaExamen) {
        this.notaExamen = notaExamen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notas_primer_parcial.promedio
     *
     * @return the value of notas_primer_parcial.promedio
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public BigDecimal getPromedio() {
        return promedio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notas_primer_parcial.promedio
     *
     * @param promedio the value for notas_primer_parcial.promedio
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public void setPromedio(BigDecimal promedio) {
        this.promedio = promedio;
    }
}