package model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class NotaPrimerParcialExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table notas_primer_parcial
     *
     * @mbg.generated Sun Nov 02 13:55:44 GMT-05:00 2025
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table notas_primer_parcial
     *
     * @mbg.generated Sun Nov 02 13:55:44 GMT-05:00 2025
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table notas_primer_parcial
     *
     * @mbg.generated Sun Nov 02 13:55:44 GMT-05:00 2025
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notas_primer_parcial
     *
     * @mbg.generated Sun Nov 02 13:55:44 GMT-05:00 2025
     */
    public NotaPrimerParcialExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notas_primer_parcial
     *
     * @mbg.generated Sun Nov 02 13:55:44 GMT-05:00 2025
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notas_primer_parcial
     *
     * @mbg.generated Sun Nov 02 13:55:44 GMT-05:00 2025
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notas_primer_parcial
     *
     * @mbg.generated Sun Nov 02 13:55:44 GMT-05:00 2025
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notas_primer_parcial
     *
     * @mbg.generated Sun Nov 02 13:55:44 GMT-05:00 2025
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notas_primer_parcial
     *
     * @mbg.generated Sun Nov 02 13:55:44 GMT-05:00 2025
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notas_primer_parcial
     *
     * @mbg.generated Sun Nov 02 13:55:44 GMT-05:00 2025
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notas_primer_parcial
     *
     * @mbg.generated Sun Nov 02 13:55:44 GMT-05:00 2025
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notas_primer_parcial
     *
     * @mbg.generated Sun Nov 02 13:55:44 GMT-05:00 2025
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notas_primer_parcial
     *
     * @mbg.generated Sun Nov 02 13:55:44 GMT-05:00 2025
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notas_primer_parcial
     *
     * @mbg.generated Sun Nov 02 13:55:44 GMT-05:00 2025
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table notas_primer_parcial
     *
     * @mbg.generated Sun Nov 02 13:55:44 GMT-05:00 2025
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdEstudianteIsNull() {
            addCriterion("id_estudiante is null");
            return (Criteria) this;
        }

        public Criteria andIdEstudianteIsNotNull() {
            addCriterion("id_estudiante is not null");
            return (Criteria) this;
        }

        public Criteria andIdEstudianteEqualTo(Integer value) {
            addCriterion("id_estudiante =", value, "idEstudiante");
            return (Criteria) this;
        }

        public Criteria andIdEstudianteNotEqualTo(Integer value) {
            addCriterion("id_estudiante <>", value, "idEstudiante");
            return (Criteria) this;
        }

        public Criteria andIdEstudianteGreaterThan(Integer value) {
            addCriterion("id_estudiante >", value, "idEstudiante");
            return (Criteria) this;
        }

        public Criteria andIdEstudianteGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_estudiante >=", value, "idEstudiante");
            return (Criteria) this;
        }

        public Criteria andIdEstudianteLessThan(Integer value) {
            addCriterion("id_estudiante <", value, "idEstudiante");
            return (Criteria) this;
        }

        public Criteria andIdEstudianteLessThanOrEqualTo(Integer value) {
            addCriterion("id_estudiante <=", value, "idEstudiante");
            return (Criteria) this;
        }

        public Criteria andIdEstudianteIn(List<Integer> values) {
            addCriterion("id_estudiante in", values, "idEstudiante");
            return (Criteria) this;
        }

        public Criteria andIdEstudianteNotIn(List<Integer> values) {
            addCriterion("id_estudiante not in", values, "idEstudiante");
            return (Criteria) this;
        }

        public Criteria andIdEstudianteBetween(Integer value1, Integer value2) {
            addCriterion("id_estudiante between", value1, value2, "idEstudiante");
            return (Criteria) this;
        }

        public Criteria andIdEstudianteNotBetween(Integer value1, Integer value2) {
            addCriterion("id_estudiante not between", value1, value2, "idEstudiante");
            return (Criteria) this;
        }

        public Criteria andIdMateriaIsNull() {
            addCriterion("id_materia is null");
            return (Criteria) this;
        }

        public Criteria andIdMateriaIsNotNull() {
            addCriterion("id_materia is not null");
            return (Criteria) this;
        }

        public Criteria andIdMateriaEqualTo(Integer value) {
            addCriterion("id_materia =", value, "idMateria");
            return (Criteria) this;
        }

        public Criteria andIdMateriaNotEqualTo(Integer value) {
            addCriterion("id_materia <>", value, "idMateria");
            return (Criteria) this;
        }

        public Criteria andIdMateriaGreaterThan(Integer value) {
            addCriterion("id_materia >", value, "idMateria");
            return (Criteria) this;
        }

        public Criteria andIdMateriaGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_materia >=", value, "idMateria");
            return (Criteria) this;
        }

        public Criteria andIdMateriaLessThan(Integer value) {
            addCriterion("id_materia <", value, "idMateria");
            return (Criteria) this;
        }

        public Criteria andIdMateriaLessThanOrEqualTo(Integer value) {
            addCriterion("id_materia <=", value, "idMateria");
            return (Criteria) this;
        }

        public Criteria andIdMateriaIn(List<Integer> values) {
            addCriterion("id_materia in", values, "idMateria");
            return (Criteria) this;
        }

        public Criteria andIdMateriaNotIn(List<Integer> values) {
            addCriterion("id_materia not in", values, "idMateria");
            return (Criteria) this;
        }

        public Criteria andIdMateriaBetween(Integer value1, Integer value2) {
            addCriterion("id_materia between", value1, value2, "idMateria");
            return (Criteria) this;
        }

        public Criteria andIdMateriaNotBetween(Integer value1, Integer value2) {
            addCriterion("id_materia not between", value1, value2, "idMateria");
            return (Criteria) this;
        }

        public Criteria andDeberesIsNull() {
            addCriterion("deberes is null");
            return (Criteria) this;
        }

        public Criteria andDeberesIsNotNull() {
            addCriterion("deberes is not null");
            return (Criteria) this;
        }

        public Criteria andDeberesEqualTo(BigDecimal value) {
            addCriterion("deberes =", value, "deberes");
            return (Criteria) this;
        }

        public Criteria andDeberesNotEqualTo(BigDecimal value) {
            addCriterion("deberes <>", value, "deberes");
            return (Criteria) this;
        }

        public Criteria andDeberesGreaterThan(BigDecimal value) {
            addCriterion("deberes >", value, "deberes");
            return (Criteria) this;
        }

        public Criteria andDeberesGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("deberes >=", value, "deberes");
            return (Criteria) this;
        }

        public Criteria andDeberesLessThan(BigDecimal value) {
            addCriterion("deberes <", value, "deberes");
            return (Criteria) this;
        }

        public Criteria andDeberesLessThanOrEqualTo(BigDecimal value) {
            addCriterion("deberes <=", value, "deberes");
            return (Criteria) this;
        }

        public Criteria andDeberesIn(List<BigDecimal> values) {
            addCriterion("deberes in", values, "deberes");
            return (Criteria) this;
        }

        public Criteria andDeberesNotIn(List<BigDecimal> values) {
            addCriterion("deberes not in", values, "deberes");
            return (Criteria) this;
        }

        public Criteria andDeberesBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("deberes between", value1, value2, "deberes");
            return (Criteria) this;
        }

        public Criteria andDeberesNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("deberes not between", value1, value2, "deberes");
            return (Criteria) this;
        }

        public Criteria andTalleresIsNull() {
            addCriterion("talleres is null");
            return (Criteria) this;
        }

        public Criteria andTalleresIsNotNull() {
            addCriterion("talleres is not null");
            return (Criteria) this;
        }

        public Criteria andTalleresEqualTo(BigDecimal value) {
            addCriterion("talleres =", value, "talleres");
            return (Criteria) this;
        }

        public Criteria andTalleresNotEqualTo(BigDecimal value) {
            addCriterion("talleres <>", value, "talleres");
            return (Criteria) this;
        }

        public Criteria andTalleresGreaterThan(BigDecimal value) {
            addCriterion("talleres >", value, "talleres");
            return (Criteria) this;
        }

        public Criteria andTalleresGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("talleres >=", value, "talleres");
            return (Criteria) this;
        }

        public Criteria andTalleresLessThan(BigDecimal value) {
            addCriterion("talleres <", value, "talleres");
            return (Criteria) this;
        }

        public Criteria andTalleresLessThanOrEqualTo(BigDecimal value) {
            addCriterion("talleres <=", value, "talleres");
            return (Criteria) this;
        }

        public Criteria andTalleresIn(List<BigDecimal> values) {
            addCriterion("talleres in", values, "talleres");
            return (Criteria) this;
        }

        public Criteria andTalleresNotIn(List<BigDecimal> values) {
            addCriterion("talleres not in", values, "talleres");
            return (Criteria) this;
        }

        public Criteria andTalleresBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("talleres between", value1, value2, "talleres");
            return (Criteria) this;
        }

        public Criteria andTalleresNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("talleres not between", value1, value2, "talleres");
            return (Criteria) this;
        }

        public Criteria andLeccionesIsNull() {
            addCriterion("lecciones is null");
            return (Criteria) this;
        }

        public Criteria andLeccionesIsNotNull() {
            addCriterion("lecciones is not null");
            return (Criteria) this;
        }

        public Criteria andLeccionesEqualTo(BigDecimal value) {
            addCriterion("lecciones =", value, "lecciones");
            return (Criteria) this;
        }

        public Criteria andLeccionesNotEqualTo(BigDecimal value) {
            addCriterion("lecciones <>", value, "lecciones");
            return (Criteria) this;
        }

        public Criteria andLeccionesGreaterThan(BigDecimal value) {
            addCriterion("lecciones >", value, "lecciones");
            return (Criteria) this;
        }

        public Criteria andLeccionesGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("lecciones >=", value, "lecciones");
            return (Criteria) this;
        }

        public Criteria andLeccionesLessThan(BigDecimal value) {
            addCriterion("lecciones <", value, "lecciones");
            return (Criteria) this;
        }

        public Criteria andLeccionesLessThanOrEqualTo(BigDecimal value) {
            addCriterion("lecciones <=", value, "lecciones");
            return (Criteria) this;
        }

        public Criteria andLeccionesIn(List<BigDecimal> values) {
            addCriterion("lecciones in", values, "lecciones");
            return (Criteria) this;
        }

        public Criteria andLeccionesNotIn(List<BigDecimal> values) {
            addCriterion("lecciones not in", values, "lecciones");
            return (Criteria) this;
        }

        public Criteria andLeccionesBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("lecciones between", value1, value2, "lecciones");
            return (Criteria) this;
        }

        public Criteria andLeccionesNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("lecciones not between", value1, value2, "lecciones");
            return (Criteria) this;
        }

        public Criteria andExamenIsNull() {
            addCriterion("examen is null");
            return (Criteria) this;
        }

        public Criteria andExamenIsNotNull() {
            addCriterion("examen is not null");
            return (Criteria) this;
        }

        public Criteria andExamenEqualTo(BigDecimal value) {
            addCriterion("examen =", value, "examen");
            return (Criteria) this;
        }

        public Criteria andExamenNotEqualTo(BigDecimal value) {
            addCriterion("examen <>", value, "examen");
            return (Criteria) this;
        }

        public Criteria andExamenGreaterThan(BigDecimal value) {
            addCriterion("examen >", value, "examen");
            return (Criteria) this;
        }

        public Criteria andExamenGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("examen >=", value, "examen");
            return (Criteria) this;
        }

        public Criteria andExamenLessThan(BigDecimal value) {
            addCriterion("examen <", value, "examen");
            return (Criteria) this;
        }

        public Criteria andExamenLessThanOrEqualTo(BigDecimal value) {
            addCriterion("examen <=", value, "examen");
            return (Criteria) this;
        }

        public Criteria andExamenIn(List<BigDecimal> values) {
            addCriterion("examen in", values, "examen");
            return (Criteria) this;
        }

        public Criteria andExamenNotIn(List<BigDecimal> values) {
            addCriterion("examen not in", values, "examen");
            return (Criteria) this;
        }

        public Criteria andExamenBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("examen between", value1, value2, "examen");
            return (Criteria) this;
        }

        public Criteria andExamenNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("examen not between", value1, value2, "examen");
            return (Criteria) this;
        }

        public Criteria andPromedioGeneralIsNull() {
            addCriterion("promedio_general is null");
            return (Criteria) this;
        }

        public Criteria andPromedioGeneralIsNotNull() {
            addCriterion("promedio_general is not null");
            return (Criteria) this;
        }

        public Criteria andPromedioGeneralEqualTo(BigDecimal value) {
            addCriterion("promedio_general =", value, "promedioGeneral");
            return (Criteria) this;
        }

        public Criteria andPromedioGeneralNotEqualTo(BigDecimal value) {
            addCriterion("promedio_general <>", value, "promedioGeneral");
            return (Criteria) this;
        }

        public Criteria andPromedioGeneralGreaterThan(BigDecimal value) {
            addCriterion("promedio_general >", value, "promedioGeneral");
            return (Criteria) this;
        }

        public Criteria andPromedioGeneralGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("promedio_general >=", value, "promedioGeneral");
            return (Criteria) this;
        }

        public Criteria andPromedioGeneralLessThan(BigDecimal value) {
            addCriterion("promedio_general <", value, "promedioGeneral");
            return (Criteria) this;
        }

        public Criteria andPromedioGeneralLessThanOrEqualTo(BigDecimal value) {
            addCriterion("promedio_general <=", value, "promedioGeneral");
            return (Criteria) this;
        }

        public Criteria andPromedioGeneralIn(List<BigDecimal> values) {
            addCriterion("promedio_general in", values, "promedioGeneral");
            return (Criteria) this;
        }

        public Criteria andPromedioGeneralNotIn(List<BigDecimal> values) {
            addCriterion("promedio_general not in", values, "promedioGeneral");
            return (Criteria) this;
        }

        public Criteria andPromedioGeneralBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("promedio_general between", value1, value2, "promedioGeneral");
            return (Criteria) this;
        }

        public Criteria andPromedioGeneralNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("promedio_general not between", value1, value2, "promedioGeneral");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table notas_primer_parcial
     *
     * @mbg.generated do_not_delete_during_merge Sun Nov 02 13:55:44 GMT-05:00 2025
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table notas_primer_parcial
     *
     * @mbg.generated Sun Nov 02 13:55:44 GMT-05:00 2025
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}