package model;

import java.math.BigDecimal;

public class NotaFinal {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NotasFinales.id
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NotasFinales.id_estudiante
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    private Integer idEstudiante;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NotasFinales.id_materia
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    private Integer idMateria;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NotasFinales.promedio_final
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    private BigDecimal promedioFinal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NotasFinales.id_estado
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    private Integer idEstado;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NotasFinales.id
     *
     * @return the value of NotasFinales.id
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NotasFinales.id
     *
     * @param id the value for NotasFinales.id
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NotasFinales.id_estudiante
     *
     * @return the value of NotasFinales.id_estudiante
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public Integer getIdEstudiante() {
        return idEstudiante;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NotasFinales.id_estudiante
     *
     * @param idEstudiante the value for NotasFinales.id_estudiante
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public void setIdEstudiante(Integer idEstudiante) {
        this.idEstudiante = idEstudiante;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NotasFinales.id_materia
     *
     * @return the value of NotasFinales.id_materia
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public Integer getIdMateria() {
        return idMateria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NotasFinales.id_materia
     *
     * @param idMateria the value for NotasFinales.id_materia
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public void setIdMateria(Integer idMateria) {
        this.idMateria = idMateria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NotasFinales.promedio_final
     *
     * @return the value of NotasFinales.promedio_final
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public BigDecimal getPromedioFinal() {
        return promedioFinal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NotasFinales.promedio_final
     *
     * @param promedioFinal the value for NotasFinales.promedio_final
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public void setPromedioFinal(BigDecimal promedioFinal) {
        this.promedioFinal = promedioFinal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NotasFinales.id_estado
     *
     * @return the value of NotasFinales.id_estado
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public Integer getIdEstado() {
        return idEstado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NotasFinales.id_estado
     *
     * @param idEstado the value for NotasFinales.id_estado
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public void setIdEstado(Integer idEstado) {
        this.idEstado = idEstado;
    }
}