package model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class NotaPrimerParcialExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table notas_primer_parcial
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table notas_primer_parcial
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table notas_primer_parcial
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notas_primer_parcial
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public NotaPrimerParcialExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notas_primer_parcial
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notas_primer_parcial
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notas_primer_parcial
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notas_primer_parcial
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notas_primer_parcial
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notas_primer_parcial
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notas_primer_parcial
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notas_primer_parcial
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notas_primer_parcial
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notas_primer_parcial
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table notas_primer_parcial
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdNotaIsNull() {
            addCriterion("id_nota is null");
            return (Criteria) this;
        }

        public Criteria andIdNotaIsNotNull() {
            addCriterion("id_nota is not null");
            return (Criteria) this;
        }

        public Criteria andIdNotaEqualTo(Integer value) {
            addCriterion("id_nota =", value, "idNota");
            return (Criteria) this;
        }

        public Criteria andIdNotaNotEqualTo(Integer value) {
            addCriterion("id_nota <>", value, "idNota");
            return (Criteria) this;
        }

        public Criteria andIdNotaGreaterThan(Integer value) {
            addCriterion("id_nota >", value, "idNota");
            return (Criteria) this;
        }

        public Criteria andIdNotaGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_nota >=", value, "idNota");
            return (Criteria) this;
        }

        public Criteria andIdNotaLessThan(Integer value) {
            addCriterion("id_nota <", value, "idNota");
            return (Criteria) this;
        }

        public Criteria andIdNotaLessThanOrEqualTo(Integer value) {
            addCriterion("id_nota <=", value, "idNota");
            return (Criteria) this;
        }

        public Criteria andIdNotaIn(List<Integer> values) {
            addCriterion("id_nota in", values, "idNota");
            return (Criteria) this;
        }

        public Criteria andIdNotaNotIn(List<Integer> values) {
            addCriterion("id_nota not in", values, "idNota");
            return (Criteria) this;
        }

        public Criteria andIdNotaBetween(Integer value1, Integer value2) {
            addCriterion("id_nota between", value1, value2, "idNota");
            return (Criteria) this;
        }

        public Criteria andIdNotaNotBetween(Integer value1, Integer value2) {
            addCriterion("id_nota not between", value1, value2, "idNota");
            return (Criteria) this;
        }

        public Criteria andIdEstudianteIsNull() {
            addCriterion("id_estudiante is null");
            return (Criteria) this;
        }

        public Criteria andIdEstudianteIsNotNull() {
            addCriterion("id_estudiante is not null");
            return (Criteria) this;
        }

        public Criteria andIdEstudianteEqualTo(Integer value) {
            addCriterion("id_estudiante =", value, "idEstudiante");
            return (Criteria) this;
        }

        public Criteria andIdEstudianteNotEqualTo(Integer value) {
            addCriterion("id_estudiante <>", value, "idEstudiante");
            return (Criteria) this;
        }

        public Criteria andIdEstudianteGreaterThan(Integer value) {
            addCriterion("id_estudiante >", value, "idEstudiante");
            return (Criteria) this;
        }

        public Criteria andIdEstudianteGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_estudiante >=", value, "idEstudiante");
            return (Criteria) this;
        }

        public Criteria andIdEstudianteLessThan(Integer value) {
            addCriterion("id_estudiante <", value, "idEstudiante");
            return (Criteria) this;
        }

        public Criteria andIdEstudianteLessThanOrEqualTo(Integer value) {
            addCriterion("id_estudiante <=", value, "idEstudiante");
            return (Criteria) this;
        }

        public Criteria andIdEstudianteIn(List<Integer> values) {
            addCriterion("id_estudiante in", values, "idEstudiante");
            return (Criteria) this;
        }

        public Criteria andIdEstudianteNotIn(List<Integer> values) {
            addCriterion("id_estudiante not in", values, "idEstudiante");
            return (Criteria) this;
        }

        public Criteria andIdEstudianteBetween(Integer value1, Integer value2) {
            addCriterion("id_estudiante between", value1, value2, "idEstudiante");
            return (Criteria) this;
        }

        public Criteria andIdEstudianteNotBetween(Integer value1, Integer value2) {
            addCriterion("id_estudiante not between", value1, value2, "idEstudiante");
            return (Criteria) this;
        }

        public Criteria andNotaDeberesIsNull() {
            addCriterion("nota_deberes is null");
            return (Criteria) this;
        }

        public Criteria andNotaDeberesIsNotNull() {
            addCriterion("nota_deberes is not null");
            return (Criteria) this;
        }

        public Criteria andNotaDeberesEqualTo(BigDecimal value) {
            addCriterion("nota_deberes =", value, "notaDeberes");
            return (Criteria) this;
        }

        public Criteria andNotaDeberesNotEqualTo(BigDecimal value) {
            addCriterion("nota_deberes <>", value, "notaDeberes");
            return (Criteria) this;
        }

        public Criteria andNotaDeberesGreaterThan(BigDecimal value) {
            addCriterion("nota_deberes >", value, "notaDeberes");
            return (Criteria) this;
        }

        public Criteria andNotaDeberesGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("nota_deberes >=", value, "notaDeberes");
            return (Criteria) this;
        }

        public Criteria andNotaDeberesLessThan(BigDecimal value) {
            addCriterion("nota_deberes <", value, "notaDeberes");
            return (Criteria) this;
        }

        public Criteria andNotaDeberesLessThanOrEqualTo(BigDecimal value) {
            addCriterion("nota_deberes <=", value, "notaDeberes");
            return (Criteria) this;
        }

        public Criteria andNotaDeberesIn(List<BigDecimal> values) {
            addCriterion("nota_deberes in", values, "notaDeberes");
            return (Criteria) this;
        }

        public Criteria andNotaDeberesNotIn(List<BigDecimal> values) {
            addCriterion("nota_deberes not in", values, "notaDeberes");
            return (Criteria) this;
        }

        public Criteria andNotaDeberesBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("nota_deberes between", value1, value2, "notaDeberes");
            return (Criteria) this;
        }

        public Criteria andNotaDeberesNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("nota_deberes not between", value1, value2, "notaDeberes");
            return (Criteria) this;
        }

        public Criteria andNotaAsistenciaIsNull() {
            addCriterion("nota_asistencia is null");
            return (Criteria) this;
        }

        public Criteria andNotaAsistenciaIsNotNull() {
            addCriterion("nota_asistencia is not null");
            return (Criteria) this;
        }

        public Criteria andNotaAsistenciaEqualTo(BigDecimal value) {
            addCriterion("nota_asistencia =", value, "notaAsistencia");
            return (Criteria) this;
        }

        public Criteria andNotaAsistenciaNotEqualTo(BigDecimal value) {
            addCriterion("nota_asistencia <>", value, "notaAsistencia");
            return (Criteria) this;
        }

        public Criteria andNotaAsistenciaGreaterThan(BigDecimal value) {
            addCriterion("nota_asistencia >", value, "notaAsistencia");
            return (Criteria) this;
        }

        public Criteria andNotaAsistenciaGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("nota_asistencia >=", value, "notaAsistencia");
            return (Criteria) this;
        }

        public Criteria andNotaAsistenciaLessThan(BigDecimal value) {
            addCriterion("nota_asistencia <", value, "notaAsistencia");
            return (Criteria) this;
        }

        public Criteria andNotaAsistenciaLessThanOrEqualTo(BigDecimal value) {
            addCriterion("nota_asistencia <=", value, "notaAsistencia");
            return (Criteria) this;
        }

        public Criteria andNotaAsistenciaIn(List<BigDecimal> values) {
            addCriterion("nota_asistencia in", values, "notaAsistencia");
            return (Criteria) this;
        }

        public Criteria andNotaAsistenciaNotIn(List<BigDecimal> values) {
            addCriterion("nota_asistencia not in", values, "notaAsistencia");
            return (Criteria) this;
        }

        public Criteria andNotaAsistenciaBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("nota_asistencia between", value1, value2, "notaAsistencia");
            return (Criteria) this;
        }

        public Criteria andNotaAsistenciaNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("nota_asistencia not between", value1, value2, "notaAsistencia");
            return (Criteria) this;
        }

        public Criteria andNotaLeccionIsNull() {
            addCriterion("nota_leccion is null");
            return (Criteria) this;
        }

        public Criteria andNotaLeccionIsNotNull() {
            addCriterion("nota_leccion is not null");
            return (Criteria) this;
        }

        public Criteria andNotaLeccionEqualTo(BigDecimal value) {
            addCriterion("nota_leccion =", value, "notaLeccion");
            return (Criteria) this;
        }

        public Criteria andNotaLeccionNotEqualTo(BigDecimal value) {
            addCriterion("nota_leccion <>", value, "notaLeccion");
            return (Criteria) this;
        }

        public Criteria andNotaLeccionGreaterThan(BigDecimal value) {
            addCriterion("nota_leccion >", value, "notaLeccion");
            return (Criteria) this;
        }

        public Criteria andNotaLeccionGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("nota_leccion >=", value, "notaLeccion");
            return (Criteria) this;
        }

        public Criteria andNotaLeccionLessThan(BigDecimal value) {
            addCriterion("nota_leccion <", value, "notaLeccion");
            return (Criteria) this;
        }

        public Criteria andNotaLeccionLessThanOrEqualTo(BigDecimal value) {
            addCriterion("nota_leccion <=", value, "notaLeccion");
            return (Criteria) this;
        }

        public Criteria andNotaLeccionIn(List<BigDecimal> values) {
            addCriterion("nota_leccion in", values, "notaLeccion");
            return (Criteria) this;
        }

        public Criteria andNotaLeccionNotIn(List<BigDecimal> values) {
            addCriterion("nota_leccion not in", values, "notaLeccion");
            return (Criteria) this;
        }

        public Criteria andNotaLeccionBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("nota_leccion between", value1, value2, "notaLeccion");
            return (Criteria) this;
        }

        public Criteria andNotaLeccionNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("nota_leccion not between", value1, value2, "notaLeccion");
            return (Criteria) this;
        }

        public Criteria andNotaExamenIsNull() {
            addCriterion("nota_examen is null");
            return (Criteria) this;
        }

        public Criteria andNotaExamenIsNotNull() {
            addCriterion("nota_examen is not null");
            return (Criteria) this;
        }

        public Criteria andNotaExamenEqualTo(BigDecimal value) {
            addCriterion("nota_examen =", value, "notaExamen");
            return (Criteria) this;
        }

        public Criteria andNotaExamenNotEqualTo(BigDecimal value) {
            addCriterion("nota_examen <>", value, "notaExamen");
            return (Criteria) this;
        }

        public Criteria andNotaExamenGreaterThan(BigDecimal value) {
            addCriterion("nota_examen >", value, "notaExamen");
            return (Criteria) this;
        }

        public Criteria andNotaExamenGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("nota_examen >=", value, "notaExamen");
            return (Criteria) this;
        }

        public Criteria andNotaExamenLessThan(BigDecimal value) {
            addCriterion("nota_examen <", value, "notaExamen");
            return (Criteria) this;
        }

        public Criteria andNotaExamenLessThanOrEqualTo(BigDecimal value) {
            addCriterion("nota_examen <=", value, "notaExamen");
            return (Criteria) this;
        }

        public Criteria andNotaExamenIn(List<BigDecimal> values) {
            addCriterion("nota_examen in", values, "notaExamen");
            return (Criteria) this;
        }

        public Criteria andNotaExamenNotIn(List<BigDecimal> values) {
            addCriterion("nota_examen not in", values, "notaExamen");
            return (Criteria) this;
        }

        public Criteria andNotaExamenBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("nota_examen between", value1, value2, "notaExamen");
            return (Criteria) this;
        }

        public Criteria andNotaExamenNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("nota_examen not between", value1, value2, "notaExamen");
            return (Criteria) this;
        }

        public Criteria andPromedioIsNull() {
            addCriterion("promedio is null");
            return (Criteria) this;
        }

        public Criteria andPromedioIsNotNull() {
            addCriterion("promedio is not null");
            return (Criteria) this;
        }

        public Criteria andPromedioEqualTo(BigDecimal value) {
            addCriterion("promedio =", value, "promedio");
            return (Criteria) this;
        }

        public Criteria andPromedioNotEqualTo(BigDecimal value) {
            addCriterion("promedio <>", value, "promedio");
            return (Criteria) this;
        }

        public Criteria andPromedioGreaterThan(BigDecimal value) {
            addCriterion("promedio >", value, "promedio");
            return (Criteria) this;
        }

        public Criteria andPromedioGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("promedio >=", value, "promedio");
            return (Criteria) this;
        }

        public Criteria andPromedioLessThan(BigDecimal value) {
            addCriterion("promedio <", value, "promedio");
            return (Criteria) this;
        }

        public Criteria andPromedioLessThanOrEqualTo(BigDecimal value) {
            addCriterion("promedio <=", value, "promedio");
            return (Criteria) this;
        }

        public Criteria andPromedioIn(List<BigDecimal> values) {
            addCriterion("promedio in", values, "promedio");
            return (Criteria) this;
        }

        public Criteria andPromedioNotIn(List<BigDecimal> values) {
            addCriterion("promedio not in", values, "promedio");
            return (Criteria) this;
        }

        public Criteria andPromedioBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("promedio between", value1, value2, "promedio");
            return (Criteria) this;
        }

        public Criteria andPromedioNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("promedio not between", value1, value2, "promedio");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table notas_primer_parcial
     *
     * @mbg.generated do_not_delete_during_merge Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table notas_primer_parcial
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}