package model;

import java.math.BigDecimal;

public class NotaSegundoParcial {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notas_segundo_parcial.id
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notas_segundo_parcial.id_estudiante
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    private Integer idEstudiante;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notas_segundo_parcial.id_materia
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    private Integer idMateria;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notas_segundo_parcial.deberes
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    private BigDecimal deberes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notas_segundo_parcial.talleres
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    private BigDecimal talleres;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notas_segundo_parcial.lecciones
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    private BigDecimal lecciones;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notas_segundo_parcial.examen
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    private BigDecimal examen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notas_segundo_parcial.promedio_general
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    private BigDecimal promedioGeneral;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notas_segundo_parcial.id
     *
     * @return the value of notas_segundo_parcial.id
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notas_segundo_parcial.id
     *
     * @param id the value for notas_segundo_parcial.id
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notas_segundo_parcial.id_estudiante
     *
     * @return the value of notas_segundo_parcial.id_estudiante
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public Integer getIdEstudiante() {
        return idEstudiante;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notas_segundo_parcial.id_estudiante
     *
     * @param idEstudiante the value for notas_segundo_parcial.id_estudiante
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public void setIdEstudiante(Integer idEstudiante) {
        this.idEstudiante = idEstudiante;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notas_segundo_parcial.id_materia
     *
     * @return the value of notas_segundo_parcial.id_materia
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public Integer getIdMateria() {
        return idMateria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notas_segundo_parcial.id_materia
     *
     * @param idMateria the value for notas_segundo_parcial.id_materia
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public void setIdMateria(Integer idMateria) {
        this.idMateria = idMateria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notas_segundo_parcial.deberes
     *
     * @return the value of notas_segundo_parcial.deberes
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public BigDecimal getDeberes() {
        return deberes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notas_segundo_parcial.deberes
     *
     * @param deberes the value for notas_segundo_parcial.deberes
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public void setDeberes(BigDecimal deberes) {
        this.deberes = deberes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notas_segundo_parcial.talleres
     *
     * @return the value of notas_segundo_parcial.talleres
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public BigDecimal getTalleres() {
        return talleres;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notas_segundo_parcial.talleres
     *
     * @param talleres the value for notas_segundo_parcial.talleres
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public void setTalleres(BigDecimal talleres) {
        this.talleres = talleres;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notas_segundo_parcial.lecciones
     *
     * @return the value of notas_segundo_parcial.lecciones
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public BigDecimal getLecciones() {
        return lecciones;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notas_segundo_parcial.lecciones
     *
     * @param lecciones the value for notas_segundo_parcial.lecciones
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public void setLecciones(BigDecimal lecciones) {
        this.lecciones = lecciones;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notas_segundo_parcial.examen
     *
     * @return the value of notas_segundo_parcial.examen
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public BigDecimal getExamen() {
        return examen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notas_segundo_parcial.examen
     *
     * @param examen the value for notas_segundo_parcial.examen
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public void setExamen(BigDecimal examen) {
        this.examen = examen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notas_segundo_parcial.promedio_general
     *
     * @return the value of notas_segundo_parcial.promedio_general
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public BigDecimal getPromedioGeneral() {
        return promedioGeneral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notas_segundo_parcial.promedio_general
     *
     * @param promedioGeneral the value for notas_segundo_parcial.promedio_general
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public void setPromedioGeneral(BigDecimal promedioGeneral) {
        this.promedioGeneral = promedioGeneral;
    }
}