package model;

public class Permiso {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permisos.id
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permisos.nombre
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    private String nombre;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permisos.id
     *
     * @return the value of permisos.id
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permisos.id
     *
     * @param id the value for permisos.id
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permisos.nombre
     *
     * @return the value of permisos.nombre
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permisos.nombre
     *
     * @param nombre the value for permisos.nombre
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
}