package model;

public class RolPermiso {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles_permisos.id
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles_permisos.rol_id
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    private Integer rolId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles_permisos.permiso_id
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    private Integer permisoId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles_permisos.id
     *
     * @return the value of roles_permisos.id
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles_permisos.id
     *
     * @param id the value for roles_permisos.id
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles_permisos.rol_id
     *
     * @return the value of roles_permisos.rol_id
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public Integer getRolId() {
        return rolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles_permisos.rol_id
     *
     * @param rolId the value for roles_permisos.rol_id
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public void setRolId(Integer rolId) {
        this.rolId = rolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles_permisos.permiso_id
     *
     * @return the value of roles_permisos.permiso_id
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public Integer getPermisoId() {
        return permisoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles_permisos.permiso_id
     *
     * @param permisoId the value for roles_permisos.permiso_id
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public void setPermisoId(Integer permisoId) {
        this.permisoId = permisoId;
    }
}