package model;

public class Usuario {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuarios.id
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuarios.nombre
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    private String nombre;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuarios.rol_id
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    private Integer rolId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuarios.id
     *
     * @return the value of usuarios.id
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuarios.id
     *
     * @param id the value for usuarios.id
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuarios.nombre
     *
     * @return the value of usuarios.nombre
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuarios.nombre
     *
     * @param nombre the value for usuarios.nombre
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuarios.rol_id
     *
     * @return the value of usuarios.rol_id
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public Integer getRolId() {
        return rolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuarios.rol_id
     *
     * @param rolId the value for usuarios.rol_id
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    public void setRolId(Integer rolId) {
        this.rolId = rolId;
    }
}