package mapper;

import java.util.List;
import model.Estado;
import model.EstadoExample;
import org.apache.ibatis.annotations.Param;

public interface EstadoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Estado
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    long countByExample(EstadoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Estado
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int deleteByExample(EstadoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Estado
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Estado
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int insert(Estado row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Estado
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int insertSelective(Estado row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Estado
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    List<Estado> selectByExample(EstadoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Estado
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    Estado selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Estado
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int updateByExampleSelective(@Param("row") Estado row, @Param("example") EstadoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Estado
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int updateByExample(@Param("row") Estado row, @Param("example") EstadoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Estado
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int updateByPrimaryKeySelective(Estado row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Estado
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int updateByPrimaryKey(Estado row);
}