package mapper;

import java.util.List;
import model.Estudiante;
import model.EstudianteExample;
import org.apache.ibatis.annotations.Param;

public interface EstudianteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Estudiantes
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    long countByExample(EstudianteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Estudiantes
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int deleteByExample(EstudianteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Estudiantes
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Estudiantes
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int insert(Estudiante row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Estudiantes
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int insertSelective(Estudiante row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Estudiantes
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    List<Estudiante> selectByExample(EstudianteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Estudiantes
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    Estudiante selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Estudiantes
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int updateByExampleSelective(@Param("row") Estudiante row, @Param("example") EstudianteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Estudiantes
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int updateByExample(@Param("row") Estudiante row, @Param("example") EstudianteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Estudiantes
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int updateByPrimaryKeySelective(Estudiante row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Estudiantes
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int updateByPrimaryKey(Estudiante row);
}