package mapper;

import java.util.List;
import model.EstudianteMateria;
import model.EstudianteMateriaExample;
import org.apache.ibatis.annotations.Param;

public interface EstudianteMateriaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Estudiantes_Materias
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    long countByExample(EstudianteMateriaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Estudiantes_Materias
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int deleteByExample(EstudianteMateriaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Estudiantes_Materias
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Estudiantes_Materias
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int insert(EstudianteMateria row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Estudiantes_Materias
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int insertSelective(EstudianteMateria row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Estudiantes_Materias
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    List<EstudianteMateria> selectByExample(EstudianteMateriaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Estudiantes_Materias
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    EstudianteMateria selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Estudiantes_Materias
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int updateByExampleSelective(@Param("row") EstudianteMateria row, @Param("example") EstudianteMateriaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Estudiantes_Materias
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int updateByExample(@Param("row") EstudianteMateria row, @Param("example") EstudianteMateriaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Estudiantes_Materias
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int updateByPrimaryKeySelective(EstudianteMateria row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Estudiantes_Materias
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int updateByPrimaryKey(EstudianteMateria row);
}