package mapper;

import java.util.List;
import model.Materia;
import model.MateriaExample;
import org.apache.ibatis.annotations.Param;

public interface MateriaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Materias
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    long countByExample(MateriaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Materias
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int deleteByExample(MateriaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Materias
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Materias
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int insert(Materia row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Materias
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int insertSelective(Materia row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Materias
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    List<Materia> selectByExample(MateriaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Materias
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    Materia selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Materias
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int updateByExampleSelective(@Param("row") Materia row, @Param("example") MateriaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Materias
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int updateByExample(@Param("row") Materia row, @Param("example") MateriaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Materias
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int updateByPrimaryKeySelective(Materia row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Materias
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int updateByPrimaryKey(Materia row);
}