package mapper;

import java.util.List;
import model.NotaFinal;
import model.NotaFinalExample;
import org.apache.ibatis.annotations.Param;

public interface NotaFinalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NotasFinales
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    long countByExample(NotaFinalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NotasFinales
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int deleteByExample(NotaFinalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NotasFinales
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NotasFinales
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int insert(NotaFinal row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NotasFinales
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int insertSelective(NotaFinal row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NotasFinales
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    List<NotaFinal> selectByExample(NotaFinalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NotasFinales
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    NotaFinal selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NotasFinales
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int updateByExampleSelective(@Param("row") NotaFinal row, @Param("example") NotaFinalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NotasFinales
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int updateByExample(@Param("row") NotaFinal row, @Param("example") NotaFinalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NotasFinales
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int updateByPrimaryKeySelective(NotaFinal row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NotasFinales
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int updateByPrimaryKey(NotaFinal row);
}