package mapper;

import java.util.List;
import model.NotaPrimerParcial;
import model.NotaPrimerParcialExample;
import org.apache.ibatis.annotations.Param;

public interface NotaPrimerParcialMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notas_primer_parcial
     *
     * @mbg.generated Sun Nov 02 13:55:44 GMT-05:00 2025
     */
    long countByExample(NotaPrimerParcialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notas_primer_parcial
     *
     * @mbg.generated Sun Nov 02 13:55:44 GMT-05:00 2025
     */
    int deleteByExample(NotaPrimerParcialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notas_primer_parcial
     *
     * @mbg.generated Sun Nov 02 13:55:44 GMT-05:00 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notas_primer_parcial
     *
     * @mbg.generated Sun Nov 02 13:55:44 GMT-05:00 2025
     */
    int insert(NotaPrimerParcial row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notas_primer_parcial
     *
     * @mbg.generated Sun Nov 02 13:55:44 GMT-05:00 2025
     */
    int insertSelective(NotaPrimerParcial row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notas_primer_parcial
     *
     * @mbg.generated Sun Nov 02 13:55:44 GMT-05:00 2025
     */
    List<NotaPrimerParcial> selectByExample(NotaPrimerParcialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notas_primer_parcial
     *
     * @mbg.generated Sun Nov 02 13:55:44 GMT-05:00 2025
     */
    NotaPrimerParcial selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notas_primer_parcial
     *
     * @mbg.generated Sun Nov 02 13:55:44 GMT-05:00 2025
     */
    int updateByExampleSelective(@Param("row") NotaPrimerParcial row, @Param("example") NotaPrimerParcialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notas_primer_parcial
     *
     * @mbg.generated Sun Nov 02 13:55:44 GMT-05:00 2025
     */
    int updateByExample(@Param("row") NotaPrimerParcial row, @Param("example") NotaPrimerParcialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notas_primer_parcial
     *
     * @mbg.generated Sun Nov 02 13:55:44 GMT-05:00 2025
     */
    int updateByPrimaryKeySelective(NotaPrimerParcial row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notas_primer_parcial
     *
     * @mbg.generated Sun Nov 02 13:55:44 GMT-05:00 2025
     */
    int updateByPrimaryKey(NotaPrimerParcial row);
}