package mapper;

import java.util.List;
import model.NotaSegundoParcial;
import model.NotaSegundoParcialExample;
import org.apache.ibatis.annotations.Param;

public interface NotaSegundoParcialMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notas_segundo_parcial
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    long countByExample(NotaSegundoParcialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notas_segundo_parcial
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int deleteByExample(NotaSegundoParcialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notas_segundo_parcial
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notas_segundo_parcial
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int insert(NotaSegundoParcial row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notas_segundo_parcial
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int insertSelective(NotaSegundoParcial row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notas_segundo_parcial
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    List<NotaSegundoParcial> selectByExample(NotaSegundoParcialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notas_segundo_parcial
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    NotaSegundoParcial selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notas_segundo_parcial
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int updateByExampleSelective(@Param("row") NotaSegundoParcial row, @Param("example") NotaSegundoParcialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notas_segundo_parcial
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int updateByExample(@Param("row") NotaSegundoParcial row, @Param("example") NotaSegundoParcialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notas_segundo_parcial
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int updateByPrimaryKeySelective(NotaSegundoParcial row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notas_segundo_parcial
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int updateByPrimaryKey(NotaSegundoParcial row);
}