package mapper;

import java.util.List;
import model.Permiso;
import model.PermisoExample;
import org.apache.ibatis.annotations.Param;

public interface PermisoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permisos
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    long countByExample(PermisoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permisos
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int deleteByExample(PermisoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permisos
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permisos
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int insert(Permiso row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permisos
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int insertSelective(Permiso row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permisos
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    List<Permiso> selectByExample(PermisoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permisos
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    Permiso selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permisos
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int updateByExampleSelective(@Param("row") Permiso row, @Param("example") PermisoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permisos
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int updateByExample(@Param("row") Permiso row, @Param("example") PermisoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permisos
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int updateByPrimaryKeySelective(Permiso row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permisos
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int updateByPrimaryKey(Permiso row);
}