package mapper;

import java.util.List;
import model.Rol;
import model.RolExample;
import org.apache.ibatis.annotations.Param;

public interface RolMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    long countByExample(RolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int deleteByExample(RolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int insert(Rol row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int insertSelective(Rol row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    List<Rol> selectByExample(RolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    Rol selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int updateByExampleSelective(@Param("row") Rol row, @Param("example") RolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int updateByExample(@Param("row") Rol row, @Param("example") RolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int updateByPrimaryKeySelective(Rol row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int updateByPrimaryKey(Rol row);

    Rol selectByNombre(String nombre);

}