package mapper;

import java.util.List;
import model.RolPermiso;
import model.RolPermisoExample;
import org.apache.ibatis.annotations.Param;

public interface RolPermisoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_permisos
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    long countByExample(RolPermisoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_permisos
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int deleteByExample(RolPermisoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_permisos
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_permisos
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int insert(RolPermiso row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_permisos
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int insertSelective(RolPermiso row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_permisos
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    List<RolPermiso> selectByExample(RolPermisoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_permisos
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    RolPermiso selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_permisos
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int updateByExampleSelective(@Param("row") RolPermiso row, @Param("example") RolPermisoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_permisos
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int updateByExample(@Param("row") RolPermiso row, @Param("example") RolPermisoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_permisos
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int updateByPrimaryKeySelective(RolPermiso row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_permisos
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int updateByPrimaryKey(RolPermiso row);
}