package mapper;

import java.util.List;
import model.Usuario;
import model.UsuarioExample;
import org.apache.ibatis.annotations.Param;

public interface UsuarioMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuarios
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    long countByExample(UsuarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuarios
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int deleteByExample(UsuarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuarios
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuarios
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int insert(Usuario row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuarios
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int insertSelective(Usuario row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuarios
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    List<Usuario> selectByExample(UsuarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuarios
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    Usuario selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuarios
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int updateByExampleSelective(@Param("row") Usuario row, @Param("example") UsuarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuarios
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int updateByExample(@Param("row") Usuario row, @Param("example") UsuarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuarios
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int updateByPrimaryKeySelective(Usuario row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuarios
     *
     * @mbg.generated Sun Nov 02 11:02:07 GMT-05:00 2025
     */
    int updateByPrimaryKey(Usuario row);
}